### ISSUE TITLE
点击exe，然后闪退

### ISSUE THREAD

**Issue by xuyu666** [zhaoyun0071/LivePortrait-windows-GUI#1]
作者您好：
我下载并解压了您的压缩包，并检查了安装路径（无中文）。后续打开exe，弹出一下命令行框后闪退，想请教下解决方法。
![image](https://github.com/zhaoyun0071/LivePortrait-windows-GUI/assets/49869475/52fca221-74f7-4611-a87b-5cc04a248893)

**Comment by zhaoyun0071** [comment]
> 作者您好：
> 我下载并解压了您的压缩包，并检查了安装路径（无中文）。后续打开exe，弹出一下命令行框后闪退，想请教下解决方法。
> ![image](https://github.com/zhaoyun0071/LivePortrait-windows-GUI/assets/49869475/52fca221-74f7-4611-a87b-5cc04a248893)
> 

exe名字改成1试试

**Comment by xuyu666** [comment]
问题依旧存在，我突突截了个图，貌似缺失包了
![image](https://github.com/zhaoyun0071/LivePortrait-windows-GUI/assets/49869475/8ab16d81-67a1-4ae9-98d5-62680cbefb74)

**Comment by zhaoyun0071** [comment]
> 问题依旧存在，我突突截了个图，貌似缺失包了
> ![image](https://github.com/zhaoyun0071/LivePortrait-windows-GUI/assets/49869475/8ab16d81-67a1-4ae9-98d5-62680cbefb74)
> 

重新解压覆盖

**Comment by xuyu666** [comment]
解压覆盖后还是这样，是不是要因为python系统环境变量相关的问题

**Comment by zhaoyun0071** [comment]
> 解压覆盖后还是这样，是不是要因为python系统环境变量相关的问题

反正不需要Python环境，只有你有问题

**Comment by xuyu666** [comment]
应该是了，谢谢
